### ISSUE TITLE
Provided HelloCommand's description does not show up

### ISSUE THREAD

**Issue by agrizzli** [dotkernel/dot-console#6]
I have set up a dk3-frontend and would like to create some custom command for console. It works! But provided description in configuration does not show up when calling ```php bin/console.php```:

```
 autocomplete    Command autocompletion setup
 hello           
 help            Get help for individual commands
 version         Display the version of the script
```

I use default configuration for command:

```php
return [
    'dot_console' => [
        //'name' => 'DotKernel Console',
        //'version' => '1.0.0',

        'commands' => [
            [
                'name' => 'hello',
                'description' => 'Hello, World! command example',
                'handler' => HelloCommand::class,
            ],
        ]
    ]
];
```

**Comment by alexmerlin** [comment]
Corrected setup instructions given by README.md file.

Note the `short_description` key that needs to be added to each command.
The content of this key is displayed when listing all commands or getting help for a specific command.
